### ISSUE TITLE
Access to array using i variable

### ISSUE THREAD

**Issue by luisllamasbinaburo** [Nucs/Regen#2]
It's possible to access and array by index, inside a for each loop?

For example, I'm not able to do that
```python
#if _REGEN
    %codes = ["code1", "code2"]
   
    %foreach codes%
        #(code[i])
    % 
#else
#endif
```
Of course, in this example I know that I can just use '#1
In the real situation I have more than one array, but I simplify the code for the question

Is that posible?

**Comment by luisllamasbinaburo** [comment]
OK, I just see that it's in the "TODO" List

**Comment by Nucs** [comment]
`codes` is a variable therefore accessible.
To get the index of the current loop, use `i`. If you have nested foreachs then the second index (usually named j) will be available as `i1` and so on.
```python
#if _REGEN
    %codes = ["code1", "code2"] 
   //both lines below output the same
    %foreach codes%
        |#(codes[i.Value])
        |#1
    % 
#else

   //both lines below output the same
        code1
        code1
        code2
        code2
#endif

```

I think your issue was the `i` is a NumberScalar

**Comment by luisllamasbinaburo** [comment]
That `#(codes[i.Value])` is exactly which  I was looking for. 
Thank you, very nice tool !
